//register messages
export const EMAIL_EXISTS = "EMAIL_EXISTS";
export const TOO_MANY_ATTEMPTS_TRY_LATER = "TOO_MANY_ATTEMPTS_TRY_LATER";
export const OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED";

//login messages
export const INVALID_PASSWORD = "INVALID_PASSWORD";
